export enum RoleType {
    USER = 'ROLE_USER',
    ADMIN = 'ROLE_ADMIN',
    ANONYMOUS = 'ROLE_ANONYMOUS',
    PORTAL = 'ROLE_ADMIN_PORTAL',
    LEARNER = 'ROLE_LEARNER',
    LECTURER = 'ROLE_LECTURER',
}
